cookie:
  expiry_days: 30
  key: randomkey 
  name: streamlit-graphrag 
credentials:
  usernames:
    sfrankl:
      email: example@uvm.edu
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Sylvan
      last_name: Franklin
      logged_in: False # Will be managed automatically
      password: veins9900 # Will be hashed automatically
      roles: 
      - admin
      - editor
      - viewer
